### ISSUE TITLE
Generated stylesheet is too big

### ISSUE THREAD

**Issue by aklajnert** [seed-rs/seed-quickstart-webpack#34]
The `PurgeCSS` doesn't work anymore. The generated stylesheet has around `1.8M` and contains all `Tailwind` classes.  
It should contain only classes that were used in the project and everything else should be removed from it.

**Comment by MartinKavik** [comment]
Context from Discord:

There were some changes recently: https://github.com/seed-rs/seed-quickstart-webpack/pull/33/files#diff-05ed1c7f99e45b485708115502a1e0f28c8547e9a9a29c1b8664f79103cf7873 I hope it hasn't broken the purge

How it works:
1. `yarn start` invokes `generate::css_classes` command https://github.com/seed-rs/seed-quickstart-webpack/blob/master/package.json#L8
2. https://github.com/seed-rs/seed-quickstart-webpack/blob/master/webpack.css_classes.config.js is loaded  and `index.css_classes.ts` is used as the entry https://github.com/seed-rs/seed-quickstart-webpack/blob/master/webpack.css_classes.config.js#L12
3. `index.css_classes.ts` imports `"../css/styles.css"` - it means webpack wakes up PostCSS (as defined in that webapck config)
4. PostCSS loads its config file - https://github.com/seed-rs/seed-quickstart-webpack/blob/master/postcss.config.js and starts to process the file https://github.com/seed-rs/seed-quickstart-webpack/blob/master/css/styles.css
5. Tailwind tools process that `styles.css` file and generates CSS classes https://github.com/seed-rs/seed-quickstart-webpack/blob/master/postcss.config.js#L6
6. PostCSS plugin `"postcss-typed-css-classes"` is invoked and it generates `css_classes.rs` according to the passed CSS classes from the Tailwind output. Also it shouldn't pass unused classes to the next PostCSS pipeline parts in the production mode. It reads `*.rs` files to discover used classes.

**Comment by aklajnert** [comment]
I've tracked down that the problem has been introduced in c6506f4d9cf729fe22eee9c72959cb946bbcac16, where `postcss-typed-css-classes` has been updated from `0.2.0` to `0.2.1`.
I've run `npm install postcss-typed-css-classes@0.2.0` - and the CSS had the correct size again.  

Unfortunately, when I ran the same `npm install` command against `master`,  the compilation failed due to an unknown field in `C` struct - probably the `css_classes.rs` is not even generated. I'll try to investigate it further, but the bug was probably introduced in `postcss-typed-css-classes`.
